// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fzycrop
float fzycrop(NumericVector inparams, NumericVector Tmax, NumericVector Tmin, NumericVector Prcp, String method);
RcppExport SEXP _fzycrop_fzycrop(SEXP inparamsSEXP, SEXP TmaxSEXP, SEXP TminSEXP, SEXP PrcpSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type inparams(inparamsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Tmax(TmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Tmin(TminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Prcp(PrcpSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(fzycrop(inparams, Tmax, Tmin, Prcp, method));
    return rcpp_result_gen;
END_RCPP
}
// fzycrop_getList
List fzycrop_getList(NumericVector inparams, NumericVector Tmax, NumericVector Tmin, NumericVector Prcp, String method);
RcppExport SEXP _fzycrop_fzycrop_getList(SEXP inparamsSEXP, SEXP TmaxSEXP, SEXP TminSEXP, SEXP PrcpSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type inparams(inparamsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Tmax(TmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Tmin(TminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Prcp(PrcpSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(fzycrop_getList(inparams, Tmax, Tmin, Prcp, method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fzycrop_fzycrop", (DL_FUNC) &_fzycrop_fzycrop, 5},
    {"_fzycrop_fzycrop_getList", (DL_FUNC) &_fzycrop_fzycrop_getList, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_fzycrop(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
