# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ecocropK <- function(inparams, Tmax, Tmin, Prcp, rainfed = TRUE) {
    .Call('_ecocropK_ecocropK', PACKAGE = 'ecocropK', inparams, Tmax, Tmin, Prcp, rainfed)
}

