# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fzycrop <- function(inparams, Tmax, Tmin, Prcp, irrig = 0L, vernal = FALSE, method = "median") {
    .Call('_fzycrop_fzycrop', PACKAGE = 'fzycrop', inparams, Tmax, Tmin, Prcp, irrig, vernal, method)
}

fzycrop_getList <- function(inparams, Tmax, Tmin, Prcp, irrig = 0L, vernal = FALSE, method = "median") {
    .Call('_fzycrop_fzycrop_getList', PACKAGE = 'fzycrop', inparams, Tmax, Tmin, Prcp, irrig, vernal, method)
}

